### ISSUE TITLE
will re-attempt when a new template is discovered

### ISSUE THREAD

**Issue by gitccastro** [bitkeks/python-netflow-v9-softflowd#11]
Good day, i was trying to collect some netflow v9 statistics, but when i try to collect them using the main.py script, i got the following error:

@usflmianexaut01:~/netflow/netflowv9/python-netflow-v9-softflowd$ python3 main.py -p 9996 -D
Starting the NetFlow listener on 0.0.0.0:9996
Received 128 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 160 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 92 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 160 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 160 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 264 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 128 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 160 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 296 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
Received 264 bytes of data from ('172.240.245.2', 57071)
Failed to decode a v9 ExportPacket - will re-attempt when a new template is discovered
^CShutting down the NetFlow listener
Received KeyboardInterrupt, passing through
@usflmianexaut01:~/netflow/netflowv9/python-netflow-v9-softflowd$ 

I dont know how to change this new template thing, is that something that needs to be changed on the router or on the server itself?. Thanks for your kind help

**Comment by gitccastro** [comment]
After a while , i began to see the flows being processed as you can see below:

Received 160 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 4 flows.
Received 160 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 4 flows.
Received 128 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 3 flows.
Received 296 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 8 flows.
Received 228 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 6 flows.
Received 128 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 3 flows.
Received 92 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 2 flows.
Received 196 bytes of data from ('172.240.245.2', 57071)
Processed a v9 ExportPacket with 5 flows.
Received 128 bytes of data from ('172.240.245.2', 

However i don't know where to check for the .json files generated by the main.py script. For now the only files generated are the .gz files as you can see below:

@usflmianexaut01:~/netflow/netflowv9/python-netflow-v9-softflowd$ ls
1576088948.gz  1576089450.gz  1576089945.gz  analyzer.py  LICENSE  main.py  netflow  README.md  setup.py  tests.py

**Comment by bitkeks** [comment]
Hi, thanks for the report! And nice to see you could figure it out without my help :100:  
For others who might look into this issue in later times, some infos:

1. Templates are sent by your exporters regularly, but not with every flow. It might take **some minutes** until the exporter re-sends its templates.
2. The **JSON output files were removed completely** and were replaced with GZIP files. The lines inside the GZIP files are still JSON formatted, but each line is its own JSON dict. The compression of this multi-dict file should reduce the introduced size overhead.

Have fun with the software!
