### ISSUE TITLE
IPFIX

### ISSUE THREAD

**Issue by schadom** [bitkeks/python-netflow-v9-softflowd#20]
Thanks for this great project. Any plans for supporting IPFIX?

**Comment by bitkeks** [comment]
Hi, thanks for the nice feedback! 
I had planned to include it some time, but am working on stability right now. The library was refactored the last two days and is now an official package on PyPI: https://pypi.org/project/netflow/
You're very welcome to experiment with IPFIX of course. Feel free to add a `netflow.ipfix` module!

**Comment by bitkeks** [comment]
@schadom regarding your mentioned issue in manuelkasper/AS-Stats#88, you said 

> Currently I'm working on ip2as-lookups

I recently built a tool which mapped `hostname` -> `IPs` -> `ASN`. Maybe you find something useful in the repo: https://github.com/bitkeks/fediverse-infra-analysis/blob/master/ip2asn.py (links to my related blog article in the README).

**Comment by schadom** [comment]
@bitkeks world is small it seems :-)  I did the same already,  a Python script which fetches the pfx2as data daily from http://data.caida.org/datasets/routing and then uses this to do IP2AS lookups.

**Comment by bitkeks** [comment]
That's good to hear! Currently investigating the diff for v9 to IPFIX. I'd also try to adapt the collector to speak TCP. And SCTP, but that might be more of a case of learning purpose..

**Comment by schadom** [comment]
It could be also an alternative do do IP2AS and AS-Name lookups via `whois.cymru.com` (https://asn.cymru.com) and store this into a file.

**Comment by bitkeks** [comment]
IPFIX is now included in the package and available to the collector. Could anyone of you test it in your setups? I'd then release a new version on PyPI with IPFIX. Thanks!

**Comment by schadom** [comment]
@bitkeks wow, that's amazing! thank you very much! will test later 👍

**Comment by bitkeks** [comment]
After adding some more tests, netflow v0.10.1 with IPFIX support is now published on PyPI: https://pypi.org/project/netflow/0.10.1/
