### ISSUE TITLE
Analyzer issue

### ISSUE THREAD

**Issue by Italianooo** [bitkeks/python-netflow-v9-softflowd#32]
Hi there!
I've got an issue while using the analyzer. I've collected some data by collector, which gain data from cisco router. When I try to analyze these data by analyzer I've got nothing. Nothing is happening.  When I used analyzer with -v parameter, I got some info like this:
![image](https://user-images.githubusercontent.com/53166213/122010111-1338cc80-cdbb-11eb-8dce-60bb2bea4c62.png)
Do anyone have any idea how to resolve this?

**Comment by Italianooo** [comment]
Solved

**Comment by bitkeks** [comment]
Hi! First up, the analyzer is pretty experimental and might not be in sync with the rest of the repo.

Could you please describe what the problem and your solution was? Maybe someone else has the same issue :slightly_smiling_face:
