### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by grafolean** [bitkeks/python-netflow-v9-softflowd#38]
Hi @bitkeks,

A bug report agains my app prompted me to upgrade this project to a newer version (thank you for adding support for V9 Options!). While upgrading, I have noticed that I have quite a few performance improvements in a separate branch that I have never made a PR for. Checking it, I saw that the changes are still relevant, so I took the liberty of opening a PR. I hope you find it useful.

The changes solve the performance issues I have encountered when running [Grafolean NetFlow bot](https://github.com/grafolean/grafolean-netflow-bot) (which uses this package) on a very busy network. I have used [PyFlame](https://github.com/uber-archive/pyflame) to generate flame charts, then analysed the parts where the app seemed to spend most time in. The last version of this branch all but removed the bottleneck. Unfortunately, this was happening over a year ago, and I no longer have access to the testing system so I was unable to test these improvements again. However looking at the code I believe the effect should still be the same.

I am certain that the code could be nicer and that even further optimizations could be achieved, so please see this PR as a set of ideas. Feel free to steal whatever you find valuable and disregard the rest. :)

Kind regards,

Anze

**Comment by bitkeks** [comment]
Great work! Thank you very much! I have applied some additional comments and extended the list of IP fields.

If you have the time to test tag v0.11.2 that would be wonderful. It contains your fixes :)
