### ISSUE TITLE
Incorrect IPFIX TemplateField type checking

### ISSUE THREAD

**Issue by bof64665** [bitkeks/python-netflow-v9-softflowd#40]
Hi,

not completely sure if actually an issue, but it seems there is bug within the datatype-check of the IPFIX TemplateFields in lines 769-785 of [ipfix.py](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L769). The datatype check in the respective lines [772](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L772), [775](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L775), and [777](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L777) are not checking for the actual datatype (i.e., `string`) of the IPFIX TemplateField but for its name (i.e., `applicationGroupName`). 

I think to fix this, line [742](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L742) should be changed to
```python
discovered_fields.append((field_type.name, field_type_id, datatype))
```

Accordingly line [769](https://github.com/bitkeks/python-netflow-v9-softflowd/blob/0e24ad9e64f749b75266a4f8093a7c88b79780dd/netflow/ipfix.py#L769) should be changed to
```python
for index, ((field_type_name, field_type_id, field_datatype), value) in enumerate(zip(discovered_fields, pack)):
```
and the aforementioned lines 772, 775, and 777 should check `field_datatype` instead of `field_type_name`.

Hope this description of the problem helps.

Best :)

**Comment by bitkeks** [comment]
Hi @bof64665,
thanks for your bug report! You are right, the name is not even needed at this point if I see it correctly. 
Commit a94ad57 implements your proposed fix and even removes the `.name`. Would you take a look? 🙂

**Comment by bof64665** [comment]
Hi @bitkeks,

looks fine to me. Thanks for fixing this issue :)
