### ISSUE TITLE
to ntop?

### ISSUE THREAD

**Issue by DocMAX** [bitkeks/python-netflow-v9-softflowd#8]
and how do i get the data into ntop?

**Comment by bitkeks** [comment]
Hi! I'm not entire sure if I see the background of your question correctly. If you came from my blog post - which mentioned ntop - I'm sorry to tell you that the software in this repo does not at all connect with ntop. It's a stand-alone application which uses `softflowd` for flow exporting. Please correct me if I'm wrong (or close the issue if that answered your question :wink: ).

**Comment by DocMAX** [comment]
question answered thx
